CREATE SCHEMA IF NOT EXISTS DWH;

DROP TABLE IF EXISTS DWH.FACT_PRICE_CHANGE;
DROP TABLE IF EXISTS DWH.FACT_SALES_TRANSACTION;
DROP TABLE IF EXISTS DWH.DIM_STORE;
DROP TABLE IF EXISTS DWH.DIM_ITEM;
DROP TABLE IF EXISTS DWH.DIM_DEPARTMENT;
DROP TABLE IF EXISTS DWH.DIM_CURRENCY;
DROP TABLE IF EXISTS DWH.DIM_DATE;

CREATE TABLE DWH.DIM_DATE(
CALENDAR_DATE DATE,
DATE_DESC VARCHAR(50),
WEEK_DAY_NBR SMALLINT,
WEEK_NUMBER SMALLINT,
WEEK_NAME VARCHAR(25),
YEAR_WEEK_NUMBER INT,
MONTH_NUMBER SMALLINT,
MONTH_NAME VARCHAR(15),
QUARTER_NUMBER SMALLINT,
QUARTER_NAME CHAR(2),
HALF_YEAR_NUMBER SMALLINT,
HALF_YEAR_NAME VARCHAR(10),
GEO_REGION_CD CHAR(2),
LATEST_FLAG BOOLEAN,
ROW_INSRT_DTTM TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE DWH.DIM_CURRENCY(
CURRENCY_ID SMALLINT,
CURRENCY_CODE VARCHAR(10),
CURRENCY_NAME VARCHAR(25),
USD_EXCHANGE_RATE DECIMAL(18,4),
LATEST_FLAG BOOLEAN,
ROW_INSRT_DTTM TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE DWH.DIM_DEPARTMENT(
DEPARTMENT_NUMBER SMALLINT,
DEPARTMENT_CATEGORY_NUMBER SMALLINT,
DEPARTMENT_SUB_CATEGORY_NUMBER INT,
DEPARTMENT_DESCRIPTION VARCHAR(50),
DEPARTMENT_CATEGORY_DESCRIPTION VARCHAR(50),
DEPARTMENT_CATEGORY_SUB_DESCRIPTION VARCHAR(50),
GEO_REGION_CD CHAR(2),
LATEST_FLAG BOOLEAN,
ROW_INSRT_DTTM TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE DWH.DIM_ITEM(
ITEM_ID INT,
GEO_REGION_CD CHAR(2),
ITEM_DESCRIPTION VARCHAR(80),
UNIQUE_PRODUCT_CD DECIMAL(18,0),
UNIQUE_PRODUCT_CD_DESC VARCHAR(80),
DEPARTMENT_NUMBER SMALLINT,
DEPARTMENT_CATEGORY_NUMBER INT,
DEPARTMENT_SUB_CATEGORY_NUMBER INT,
VENDOR_NAME VARCHAR(80),
VENDOR_NUMBER INT,
ITEM_STATUS_CD CHAR(1),
ITEM_STATUS_DESC VARCHAR(50),
UNIT_COST DECIMAL(15,2),
LATEST_FLAG BOOLEAN,
ROW_INSRT_DTTM TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE DWH.DIM_STORE(
STORE_ID INT,
GEO_REGION_CD CHAR(2),
STORE_NAME VARCHAR(100),
SUB_DIVISION_NAME VARCHAR(25),
SUB_DIVISION_NUMBER CHAR(1),
REGION_NUMBER SMALLINT ,
REGION_NAME VARCHAR(100),
MARKET_NUMBER SMALLINT,
MARKET_NAME VARCHAR(100),
CITY_NAME VARCHAR(80),
OPEN_DATE DATE,
OPEN_STATUS_DESC VARCHAR(200),
POSTAL_CD INT,
STATE_PROV_CD CHAR(2),
LATEST_FLAG BOOLEAN,
ROW_INSRT_DTTM TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE DWH.FACT_SALES_TRANSACTION(
SALES_ID INT,
SALES_DATE DATE,
STORE_ID INT,
ITEM_ID INT,
SCAN_TYPE SMALLINT,
GEO_REGION_CD CHAR(2),
CURRENCY_CODE VARCHAR(10),
SCAN_ID INT,
SOLD_UNIT_QUANTITY DECIMAL(9,2),
SCAN_DATE DATE,
SCAN_TIME TIME,
SCAN_DEPT_NBR SMALLINT,
LATEST_FLAG BOOLEAN,
ROW_INSRT_DTTM TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE DWH.FACT_PRICE_CHANGE(
ITEM_ID INT,
STORE_ID INT,
PRIC_CHNG_ACTIVTN_TS TIMESTAMP,
GEO_REGION_CD CHAR(2),
PRIC_CHG_RSN VARCHAR(100),
BUSINESS_DATE DATE,
PREV_PRICE_AMT DECIMAL(15,2),
CURR_PRICE_AMT DECIMAL(15,2),
LATEST_FLAG BOOLEAN
);